# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ccong/Desktop/RobotVision

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ccong/Desktop/RobotVision

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ccong/Desktop/RobotVision/CMakeFiles /home/ccong/Desktop/RobotVision/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ccong/Desktop/RobotVision/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wv-basic-roi

# Build rule for target.
wv-basic-roi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wv-basic-roi
.PHONY : wv-basic-roi

# fast build rule for target.
wv-basic-roi/fast:
	$(MAKE) -f CMakeFiles/wv-basic-roi.dir/build.make CMakeFiles/wv-basic-roi.dir/build
.PHONY : wv-basic-roi/fast

#=============================================================================
# Target rules for targets named wv-onnx-inferring

# Build rule for target.
wv-onnx-inferring: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wv-onnx-inferring
.PHONY : wv-onnx-inferring

# fast build rule for target.
wv-onnx-inferring/fast:
	$(MAKE) -f CMakeFiles/wv-onnx-inferring.dir/build.make CMakeFiles/wv-onnx-inferring.dir/build
.PHONY : wv-onnx-inferring/fast

#=============================================================================
# Target rules for targets named wv-video-record

# Build rule for target.
wv-video-record: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wv-video-record
.PHONY : wv-video-record

# fast build rule for target.
wv-video-record/fast:
	$(MAKE) -f CMakeFiles/wv-video-record.dir/build.make CMakeFiles/wv-video-record.dir/build
.PHONY : wv-video-record/fast

#=============================================================================
# Target rules for targets named wv-basic-kalman

# Build rule for target.
wv-basic-kalman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wv-basic-kalman
.PHONY : wv-basic-kalman

# fast build rule for target.
wv-basic-kalman/fast:
	$(MAKE) -f CMakeFiles/wv-basic-kalman.dir/build.make CMakeFiles/wv-basic-kalman.dir/build
.PHONY : wv-basic-kalman/fast

#=============================================================================
# Target rules for targets named wv-fan-armor

# Build rule for target.
wv-fan-armor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wv-fan-armor
.PHONY : wv-fan-armor

# fast build rule for target.
wv-fan-armor/fast:
	$(MAKE) -f CMakeFiles/wv-fan-armor.dir/build.make CMakeFiles/wv-fan-armor.dir/build
.PHONY : wv-fan-armor/fast

#=============================================================================
# Target rules for targets named wv-basic-armor

# Build rule for target.
wv-basic-armor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wv-basic-armor
.PHONY : wv-basic-armor

# fast build rule for target.
wv-basic-armor/fast:
	$(MAKE) -f CMakeFiles/wv-basic-armor.dir/build.make CMakeFiles/wv-basic-armor.dir/build
.PHONY : wv-basic-armor/fast

#=============================================================================
# Target rules for targets named wv-basic-buff

# Build rule for target.
wv-basic-buff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wv-basic-buff
.PHONY : wv-basic-buff

# fast build rule for target.
wv-basic-buff/fast:
	$(MAKE) -f CMakeFiles/wv-basic-buff.dir/build.make CMakeFiles/wv-basic-buff.dir/build
.PHONY : wv-basic-buff/fast

#=============================================================================
# Target rules for targets named wv-basic-pnp

# Build rule for target.
wv-basic-pnp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wv-basic-pnp
.PHONY : wv-basic-pnp

# fast build rule for target.
wv-basic-pnp/fast:
	$(MAKE) -f CMakeFiles/wv-basic-pnp.dir/build.make CMakeFiles/wv-basic-pnp.dir/build
.PHONY : wv-basic-pnp/fast

#=============================================================================
# Target rules for targets named RobotVision

# Build rule for target.
RobotVision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RobotVision
.PHONY : RobotVision

# fast build rule for target.
RobotVision/fast:
	$(MAKE) -f CMakeFiles/RobotVision.dir/build.make CMakeFiles/RobotVision.dir/build
.PHONY : RobotVision/fast

#=============================================================================
# Target rules for targets named wv-uart-serial

# Build rule for target.
wv-uart-serial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wv-uart-serial
.PHONY : wv-uart-serial

# fast build rule for target.
wv-uart-serial/fast:
	$(MAKE) -f CMakeFiles/wv-uart-serial.dir/build.make CMakeFiles/wv-uart-serial.dir/build
.PHONY : wv-uart-serial/fast

#=============================================================================
# Target rules for targets named wv-mv-video-capture

# Build rule for target.
wv-mv-video-capture: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wv-mv-video-capture
.PHONY : wv-mv-video-capture

# fast build rule for target.
wv-mv-video-capture/fast:
	$(MAKE) -f CMakeFiles/wv-mv-video-capture.dir/build.make CMakeFiles/wv-mv-video-capture.dir/build
.PHONY : wv-mv-video-capture/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) -f 3rdparty/fmt/CMakeFiles/fmt.dir/build.make 3rdparty/fmt/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

base/RobotVision.o: base/RobotVision.cpp.o

.PHONY : base/RobotVision.o

# target to build an object file
base/RobotVision.cpp.o:
	$(MAKE) -f CMakeFiles/RobotVision.dir/build.make CMakeFiles/RobotVision.dir/base/RobotVision.cpp.o
.PHONY : base/RobotVision.cpp.o

base/RobotVision.i: base/RobotVision.cpp.i

.PHONY : base/RobotVision.i

# target to preprocess a source file
base/RobotVision.cpp.i:
	$(MAKE) -f CMakeFiles/RobotVision.dir/build.make CMakeFiles/RobotVision.dir/base/RobotVision.cpp.i
.PHONY : base/RobotVision.cpp.i

base/RobotVision.s: base/RobotVision.cpp.s

.PHONY : base/RobotVision.s

# target to generate assembly for a file
base/RobotVision.cpp.s:
	$(MAKE) -f CMakeFiles/RobotVision.dir/build.make CMakeFiles/RobotVision.dir/base/RobotVision.cpp.s
.PHONY : base/RobotVision.cpp.s

devices/camera/mv_video_capture.o: devices/camera/mv_video_capture.cpp.o

.PHONY : devices/camera/mv_video_capture.o

# target to build an object file
devices/camera/mv_video_capture.cpp.o:
	$(MAKE) -f CMakeFiles/wv-mv-video-capture.dir/build.make CMakeFiles/wv-mv-video-capture.dir/devices/camera/mv_video_capture.cpp.o
.PHONY : devices/camera/mv_video_capture.cpp.o

devices/camera/mv_video_capture.i: devices/camera/mv_video_capture.cpp.i

.PHONY : devices/camera/mv_video_capture.i

# target to preprocess a source file
devices/camera/mv_video_capture.cpp.i:
	$(MAKE) -f CMakeFiles/wv-mv-video-capture.dir/build.make CMakeFiles/wv-mv-video-capture.dir/devices/camera/mv_video_capture.cpp.i
.PHONY : devices/camera/mv_video_capture.cpp.i

devices/camera/mv_video_capture.s: devices/camera/mv_video_capture.cpp.s

.PHONY : devices/camera/mv_video_capture.s

# target to generate assembly for a file
devices/camera/mv_video_capture.cpp.s:
	$(MAKE) -f CMakeFiles/wv-mv-video-capture.dir/build.make CMakeFiles/wv-mv-video-capture.dir/devices/camera/mv_video_capture.cpp.s
.PHONY : devices/camera/mv_video_capture.cpp.s

devices/serial/uart_serial.o: devices/serial/uart_serial.cpp.o

.PHONY : devices/serial/uart_serial.o

# target to build an object file
devices/serial/uart_serial.cpp.o:
	$(MAKE) -f CMakeFiles/wv-uart-serial.dir/build.make CMakeFiles/wv-uart-serial.dir/devices/serial/uart_serial.cpp.o
.PHONY : devices/serial/uart_serial.cpp.o

devices/serial/uart_serial.i: devices/serial/uart_serial.cpp.i

.PHONY : devices/serial/uart_serial.i

# target to preprocess a source file
devices/serial/uart_serial.cpp.i:
	$(MAKE) -f CMakeFiles/wv-uart-serial.dir/build.make CMakeFiles/wv-uart-serial.dir/devices/serial/uart_serial.cpp.i
.PHONY : devices/serial/uart_serial.cpp.i

devices/serial/uart_serial.s: devices/serial/uart_serial.cpp.s

.PHONY : devices/serial/uart_serial.s

# target to generate assembly for a file
devices/serial/uart_serial.cpp.s:
	$(MAKE) -f CMakeFiles/wv-uart-serial.dir/build.make CMakeFiles/wv-uart-serial.dir/devices/serial/uart_serial.cpp.s
.PHONY : devices/serial/uart_serial.cpp.s

module/angle_solve/basic_pnp.o: module/angle_solve/basic_pnp.cpp.o

.PHONY : module/angle_solve/basic_pnp.o

# target to build an object file
module/angle_solve/basic_pnp.cpp.o:
	$(MAKE) -f CMakeFiles/wv-basic-pnp.dir/build.make CMakeFiles/wv-basic-pnp.dir/module/angle_solve/basic_pnp.cpp.o
.PHONY : module/angle_solve/basic_pnp.cpp.o

module/angle_solve/basic_pnp.i: module/angle_solve/basic_pnp.cpp.i

.PHONY : module/angle_solve/basic_pnp.i

# target to preprocess a source file
module/angle_solve/basic_pnp.cpp.i:
	$(MAKE) -f CMakeFiles/wv-basic-pnp.dir/build.make CMakeFiles/wv-basic-pnp.dir/module/angle_solve/basic_pnp.cpp.i
.PHONY : module/angle_solve/basic_pnp.cpp.i

module/angle_solve/basic_pnp.s: module/angle_solve/basic_pnp.cpp.s

.PHONY : module/angle_solve/basic_pnp.s

# target to generate assembly for a file
module/angle_solve/basic_pnp.cpp.s:
	$(MAKE) -f CMakeFiles/wv-basic-pnp.dir/build.make CMakeFiles/wv-basic-pnp.dir/module/angle_solve/basic_pnp.cpp.s
.PHONY : module/angle_solve/basic_pnp.cpp.s

module/armor/basic_armor.o: module/armor/basic_armor.cpp.o

.PHONY : module/armor/basic_armor.o

# target to build an object file
module/armor/basic_armor.cpp.o:
	$(MAKE) -f CMakeFiles/wv-basic-armor.dir/build.make CMakeFiles/wv-basic-armor.dir/module/armor/basic_armor.cpp.o
.PHONY : module/armor/basic_armor.cpp.o

module/armor/basic_armor.i: module/armor/basic_armor.cpp.i

.PHONY : module/armor/basic_armor.i

# target to preprocess a source file
module/armor/basic_armor.cpp.i:
	$(MAKE) -f CMakeFiles/wv-basic-armor.dir/build.make CMakeFiles/wv-basic-armor.dir/module/armor/basic_armor.cpp.i
.PHONY : module/armor/basic_armor.cpp.i

module/armor/basic_armor.s: module/armor/basic_armor.cpp.s

.PHONY : module/armor/basic_armor.s

# target to generate assembly for a file
module/armor/basic_armor.cpp.s:
	$(MAKE) -f CMakeFiles/wv-basic-armor.dir/build.make CMakeFiles/wv-basic-armor.dir/module/armor/basic_armor.cpp.s
.PHONY : module/armor/basic_armor.cpp.s

module/armor/fan_armor.o: module/armor/fan_armor.cpp.o

.PHONY : module/armor/fan_armor.o

# target to build an object file
module/armor/fan_armor.cpp.o:
	$(MAKE) -f CMakeFiles/wv-fan-armor.dir/build.make CMakeFiles/wv-fan-armor.dir/module/armor/fan_armor.cpp.o
.PHONY : module/armor/fan_armor.cpp.o

module/armor/fan_armor.i: module/armor/fan_armor.cpp.i

.PHONY : module/armor/fan_armor.i

# target to preprocess a source file
module/armor/fan_armor.cpp.i:
	$(MAKE) -f CMakeFiles/wv-fan-armor.dir/build.make CMakeFiles/wv-fan-armor.dir/module/armor/fan_armor.cpp.i
.PHONY : module/armor/fan_armor.cpp.i

module/armor/fan_armor.s: module/armor/fan_armor.cpp.s

.PHONY : module/armor/fan_armor.s

# target to generate assembly for a file
module/armor/fan_armor.cpp.s:
	$(MAKE) -f CMakeFiles/wv-fan-armor.dir/build.make CMakeFiles/wv-fan-armor.dir/module/armor/fan_armor.cpp.s
.PHONY : module/armor/fan_armor.cpp.s

module/buff/basic_buff.o: module/buff/basic_buff.cpp.o

.PHONY : module/buff/basic_buff.o

# target to build an object file
module/buff/basic_buff.cpp.o:
	$(MAKE) -f CMakeFiles/wv-basic-buff.dir/build.make CMakeFiles/wv-basic-buff.dir/module/buff/basic_buff.cpp.o
.PHONY : module/buff/basic_buff.cpp.o

module/buff/basic_buff.i: module/buff/basic_buff.cpp.i

.PHONY : module/buff/basic_buff.i

# target to preprocess a source file
module/buff/basic_buff.cpp.i:
	$(MAKE) -f CMakeFiles/wv-basic-buff.dir/build.make CMakeFiles/wv-basic-buff.dir/module/buff/basic_buff.cpp.i
.PHONY : module/buff/basic_buff.cpp.i

module/buff/basic_buff.s: module/buff/basic_buff.cpp.s

.PHONY : module/buff/basic_buff.s

# target to generate assembly for a file
module/buff/basic_buff.cpp.s:
	$(MAKE) -f CMakeFiles/wv-basic-buff.dir/build.make CMakeFiles/wv-basic-buff.dir/module/buff/basic_buff.cpp.s
.PHONY : module/buff/basic_buff.cpp.s

module/filter/basic_kalman.o: module/filter/basic_kalman.cpp.o

.PHONY : module/filter/basic_kalman.o

# target to build an object file
module/filter/basic_kalman.cpp.o:
	$(MAKE) -f CMakeFiles/wv-basic-kalman.dir/build.make CMakeFiles/wv-basic-kalman.dir/module/filter/basic_kalman.cpp.o
.PHONY : module/filter/basic_kalman.cpp.o

module/filter/basic_kalman.i: module/filter/basic_kalman.cpp.i

.PHONY : module/filter/basic_kalman.i

# target to preprocess a source file
module/filter/basic_kalman.cpp.i:
	$(MAKE) -f CMakeFiles/wv-basic-kalman.dir/build.make CMakeFiles/wv-basic-kalman.dir/module/filter/basic_kalman.cpp.i
.PHONY : module/filter/basic_kalman.cpp.i

module/filter/basic_kalman.s: module/filter/basic_kalman.cpp.s

.PHONY : module/filter/basic_kalman.s

# target to generate assembly for a file
module/filter/basic_kalman.cpp.s:
	$(MAKE) -f CMakeFiles/wv-basic-kalman.dir/build.make CMakeFiles/wv-basic-kalman.dir/module/filter/basic_kalman.cpp.s
.PHONY : module/filter/basic_kalman.cpp.s

module/ml/onnx_inferring.o: module/ml/onnx_inferring.cpp.o

.PHONY : module/ml/onnx_inferring.o

# target to build an object file
module/ml/onnx_inferring.cpp.o:
	$(MAKE) -f CMakeFiles/wv-onnx-inferring.dir/build.make CMakeFiles/wv-onnx-inferring.dir/module/ml/onnx_inferring.cpp.o
.PHONY : module/ml/onnx_inferring.cpp.o

module/ml/onnx_inferring.i: module/ml/onnx_inferring.cpp.i

.PHONY : module/ml/onnx_inferring.i

# target to preprocess a source file
module/ml/onnx_inferring.cpp.i:
	$(MAKE) -f CMakeFiles/wv-onnx-inferring.dir/build.make CMakeFiles/wv-onnx-inferring.dir/module/ml/onnx_inferring.cpp.i
.PHONY : module/ml/onnx_inferring.cpp.i

module/ml/onnx_inferring.s: module/ml/onnx_inferring.cpp.s

.PHONY : module/ml/onnx_inferring.s

# target to generate assembly for a file
module/ml/onnx_inferring.cpp.s:
	$(MAKE) -f CMakeFiles/wv-onnx-inferring.dir/build.make CMakeFiles/wv-onnx-inferring.dir/module/ml/onnx_inferring.cpp.s
.PHONY : module/ml/onnx_inferring.cpp.s

module/record/record.o: module/record/record.cpp.o

.PHONY : module/record/record.o

# target to build an object file
module/record/record.cpp.o:
	$(MAKE) -f CMakeFiles/wv-video-record.dir/build.make CMakeFiles/wv-video-record.dir/module/record/record.cpp.o
.PHONY : module/record/record.cpp.o

module/record/record.i: module/record/record.cpp.i

.PHONY : module/record/record.i

# target to preprocess a source file
module/record/record.cpp.i:
	$(MAKE) -f CMakeFiles/wv-video-record.dir/build.make CMakeFiles/wv-video-record.dir/module/record/record.cpp.i
.PHONY : module/record/record.cpp.i

module/record/record.s: module/record/record.cpp.s

.PHONY : module/record/record.s

# target to generate assembly for a file
module/record/record.cpp.s:
	$(MAKE) -f CMakeFiles/wv-video-record.dir/build.make CMakeFiles/wv-video-record.dir/module/record/record.cpp.s
.PHONY : module/record/record.cpp.s

module/roi/basic_roi.o: module/roi/basic_roi.cpp.o

.PHONY : module/roi/basic_roi.o

# target to build an object file
module/roi/basic_roi.cpp.o:
	$(MAKE) -f CMakeFiles/wv-basic-roi.dir/build.make CMakeFiles/wv-basic-roi.dir/module/roi/basic_roi.cpp.o
.PHONY : module/roi/basic_roi.cpp.o

module/roi/basic_roi.i: module/roi/basic_roi.cpp.i

.PHONY : module/roi/basic_roi.i

# target to preprocess a source file
module/roi/basic_roi.cpp.i:
	$(MAKE) -f CMakeFiles/wv-basic-roi.dir/build.make CMakeFiles/wv-basic-roi.dir/module/roi/basic_roi.cpp.i
.PHONY : module/roi/basic_roi.cpp.i

module/roi/basic_roi.s: module/roi/basic_roi.cpp.s

.PHONY : module/roi/basic_roi.s

# target to generate assembly for a file
module/roi/basic_roi.cpp.s:
	$(MAKE) -f CMakeFiles/wv-basic-roi.dir/build.make CMakeFiles/wv-basic-roi.dir/module/roi/basic_roi.cpp.s
.PHONY : module/roi/basic_roi.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... wv-basic-roi"
	@echo "... wv-onnx-inferring"
	@echo "... wv-video-record"
	@echo "... wv-basic-kalman"
	@echo "... wv-fan-armor"
	@echo "... edit_cache"
	@echo "... wv-basic-armor"
	@echo "... wv-basic-buff"
	@echo "... wv-basic-pnp"
	@echo "... rebuild_cache"
	@echo "... RobotVision"
	@echo "... wv-uart-serial"
	@echo "... wv-mv-video-capture"
	@echo "... fmt"
	@echo "... base/RobotVision.o"
	@echo "... base/RobotVision.i"
	@echo "... base/RobotVision.s"
	@echo "... devices/camera/mv_video_capture.o"
	@echo "... devices/camera/mv_video_capture.i"
	@echo "... devices/camera/mv_video_capture.s"
	@echo "... devices/serial/uart_serial.o"
	@echo "... devices/serial/uart_serial.i"
	@echo "... devices/serial/uart_serial.s"
	@echo "... module/angle_solve/basic_pnp.o"
	@echo "... module/angle_solve/basic_pnp.i"
	@echo "... module/angle_solve/basic_pnp.s"
	@echo "... module/armor/basic_armor.o"
	@echo "... module/armor/basic_armor.i"
	@echo "... module/armor/basic_armor.s"
	@echo "... module/armor/fan_armor.o"
	@echo "... module/armor/fan_armor.i"
	@echo "... module/armor/fan_armor.s"
	@echo "... module/buff/basic_buff.o"
	@echo "... module/buff/basic_buff.i"
	@echo "... module/buff/basic_buff.s"
	@echo "... module/filter/basic_kalman.o"
	@echo "... module/filter/basic_kalman.i"
	@echo "... module/filter/basic_kalman.s"
	@echo "... module/ml/onnx_inferring.o"
	@echo "... module/ml/onnx_inferring.i"
	@echo "... module/ml/onnx_inferring.s"
	@echo "... module/record/record.o"
	@echo "... module/record/record.i"
	@echo "... module/record/record.s"
	@echo "... module/roi/basic_roi.o"
	@echo "... module/roi/basic_roi.i"
	@echo "... module/roi/basic_roi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

